### ISSUE TITLE
How to send back the command to device that are stored in gts db table ?

### ISSUE THREAD

**Issue by prashant075** [neeph/OpenGTSFull#1]
Hi ,
I have a sets of command that are stored in db in one of the gts table.
I want to send this command back to device .
Please help me or given some idea to solve this problem.
(I am able to send the command via a trackhandler java code but it's set by server side or me , now i need this command set by web interface and that will store in db , if packet will come I have to get back the command to particular device )
@neeph 

Thank You.

**Comment by alvaroffj** [comment]
Hi, the only way to send commands to the device is via SMS, for that you could use a SMS API to send the command.

**Comment by prashant075** [comment]
This is possible to send command via tcp protocol. But I don't know the exact way who to implement this features. 
Thanks @neeph
